apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: voting-app   # Add your desired namespace here
  labels:
    name: redis-pod
    app: demo-voting-app
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379